export type MAJOR_TYPE = "HUMANITIES" | "SOCIETY" | "EDUCATION" | "ENGINEERING" | "NATURE" | "MEDICINE" | "PHYSICAL";
export const MAJOR_TYPE_LIST: MAJOR_TYPE[] = [
  "HUMANITIES",
  "SOCIETY",
  "EDUCATION",
  "ENGINEERING",
  "NATURE",
  "MEDICINE",
  "PHYSICAL",
];
