import type { Metadata } from "next";
import Layout from "@/components/common/layout";
import StyledComponentsRegistry from "src/libs/registry";
import { RecoilRoot } from "recoil";
export const metadata: Metadata = {
  title: "Dear",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Layout>{children}</Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
