import type { Metadata } from "next";
import Layout from "src/components/common/layout/index";
import StyledComponentsRegistry from "src/Libs/registry";
import GlobalStyle from "src/style/global";
export const metadata: Metadata = {
  title: "Dear",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyle />
          <Layout>{children}</Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
